author: &author Canberra Girls' Programming Network
title: *author
email: canberragpn@gmail.com
description: The Canberra branch of GPN Australia
baseurl: ''
github: http://github.com/canberragpn
imgdir: /static/img
logo: gpn-square-yellow.svg

menu-items:
- text: Home
  url: /
- text: News
  url: /news/
  layout: post
- text: Register
  url: /register/
- text: Workshops
  url: /workshops/
# - text: FAQ
#   url: /faq/
- text: Contact
  url: /contact/

collections:
  workshops:
    output: true

sass:
  style: compressed

# Build settings
markdown: kramdown
exclude:
- Gemfile
- Gemfile.lock
